### ISSUE TITLE
Sprint 2 presentation 

### ISSUE THREAD

**Issue by daloff** [Library-Of-Congress-Image-Checker/House-Of-Congress#18]
due 10/21

**Comment by jeremiah10z** [comment]
Wireframe Screenshots
![Screenshot (59)](https://user-images.githubusercontent.com/55027930/67031205-042de280-f0df-11e9-858b-cb77f1770e2b.png)
![Screenshot (60)](https://user-images.githubusercontent.com/55027930/67031216-0b54f080-f0df-11e9-91f1-ca63d773b523.png)
![Screenshot (61)](https://user-images.githubusercontent.com/55027930/67031219-0d1eb400-f0df-11e9-92cd-fdc019cdef07.png)
